config/routes.rb
Rails.application.routes.draw do
  get 'menus/index'

  get 'admin/index'

  devise_for :users

  resources :admin
  resources :menus
  resources :emails

  get 'static_pages/index'


  get 'admin/:id' => 'admin#show'

  get '/menu' => 'static_pages#menu'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  root 'static_pages#index'

  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email.rb
class Email < ApplicationRecord
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

	before_action :authenticate_user!


  def index
  end


  def show
  	@admin = current_user
  	@menu = Menu.find(params[:id])
  end


  def create_menu

  	@admin = current_user


  end

  def product_destroy
    @menu = Menu.find(params[:id])
    @menu.delete(@menu)
    redirect_to admin_path

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController

	def index
	end


	def create
		Email.create(email_params)
		flash[:notice] = "THank you!"
		redirect_to '/'

	end


	private

	def email_params
	    params.require(:email).permit(:fname, :lname, :email)
	  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

	before_action :authenticate_user!


  def index
  end


  def edit 
  	@menu = Menu.find(params[:id])


  end

  def create
  	Menu.create(menu_params)

  end


  def update
  	@menu = Menu.find(params[:id])
  	@menu.update(menu_params)
  	redirect_to admin_path


  end

  def product_destroy
    @menu = Menu.find(params[:id])
    @menu.delete(@menu)
    redirect_to admin_path

  end



  private

	  def menu_params
	    params.require(:menu).permit(:menu_item, :price, :description, :category)
	  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/email_helper.rb
module EmailHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>

app/views/admin/show.html.erb
<div class="container">

		<center><h2>Admin Center</h2>
		<br />
		<h3>Welcome <%= current_user.email %></h3>
		</center>

	<%= link_to('Add Menu Item', new_menu_path, :class => 'btn btn-danger') %>
	<%= link_to('Logout', destroy_user_session_path, :method => :delete, :class => 'btn btn-danger') %>

	<div class="row">
		<h1> Breakfast Items</h1>

		<% Menu.where(category: 'Breakfast').all.each do |breakfast| %>
		<div class="col-md-2 menu-item">
		<div class="margin-text"></div>
			Name: <%= breakfast.menu_item %><br>
			Category: <%= breakfast.category %><br>
			Description: <%= breakfast.description %><br>
			Price: <%= breakfast.price %><br><br>

			<center><a href="/menus/<%= breakfast.id %>/edit" class="btn content-btn " style="color:white">Edit Item</a><br></center>
		</div>
			


		<% end %>
	</div>


	<div class="row">
		<h2>Paninis </h2>
		<% Menu.where(category: 'Paninis').all.each do |panini| %>
		<div class="col-md-2 menu-item">
		<div class="margin-text"></div>
			Name: <%= panini.menu_item %><br>
			Category: <%= panini.category %><br>
			Description: <%= panini.description %><br>
			Price: <%= panini.price %><br><br>
			<center><a href="/menus/<%= panini.id %>/edit" class="btn content-btn" style="color:white">Edit Item</a><br><br></center>
		</div>

		<% end %>
	</div>

	<div class="row">
		<h2>Salads </h2>
		

		<% Menu.where(category: 'Salads').all.each do |salad| %>
		<div class="col-md-2 menu-item">
		<div class="margin-text"></div>
			Name: <%= salad.menu_item %><br>
			Category: <%= salad.category %><br>
			Description: <%= salad.description %><br>
			Price: <%= salad.price %><br><br>
			<center><a href="/menus/<%= salad.id %>/edit" class="btn content-btn" style="color:white">Edit Item</a><br><br></center>
		</div>

		<% end %>
	</div>
<br>



<h2> Emails </h2>
	<% Email.all.each do |email| %>
		Name: <%= email.fname %><br>
		Last Name: <%= email.lname %><br>
		Email: <%= email.email %>
	<% end %>



	api key: AIzaSyDQxxFBgvR3G8TaQ7Eg7xwD2pRxZsX1bNk

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Cubbyholenj</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">
	</head>
	<body>
		<%= yield %>
		<footer>
			<div class="footer-wrap">
				<div class="container">
					<div class="footer">
						<div class="row">
							<div class="margin-text"></div>
							<div class="col-md-4 col-md-offset-4 footer-social">
								
								<i class="fa fa-facebook"></i>
								<i class="fa fa-twitter"></i>
								<i class="fa fa-instagram"></i>
								<i class="fa fa-snapchat"></i>
							</div>
						</div>
						<div class="row">
							<div class="margin-text"></div>
							<div class="col-md-12 footer-text">
								2017 The Cubby Hole <Br> Website  by  michael welsh <br><a href="/users/sign_in">Admin</a>
								<br>
								<% if current_user %>
								<a href="/admin/<%= current_user.id.to_s %>">Admin Page</a></li><br>
								<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
								<% end %>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</footer>
	</body>
</html>

app/views/menus/edit.html.erb
<div class="container">
		<div class="row">
			<div class="col-md-5 col-md-offset-3">


				<%= form_for @menu do |f| %>

				<h2>Edit Menu Item</h2>

					<%= f.hidden_field :id, value: @menu.id %>
					<%= f.label :menu_item, value: 'Item Name' %>
					<%= f.text_field :menu_item, :class => 'form-control' %><br />

					<%= f.label :category, value: 'Category' %>
					<% categories = ["Breakfast", "Paninis", "Salads"] %>
					<%= f.select(:category, options_for_select(categories)) %><br />

					<%= f.label :description, value: 'Description (information about the menu item)'%>
					<%= f.text_field :description, :class => 'form-control' %><br />

					<%= f.label :price, value: 'Price (Decimal)' %>
					<%= f.text_field :price, :class => 'form-control' %><br />





					<%= f.submit 'Edit Item', :class => 'btn content-btn form-control' %>
				<% end %>
				<br />
					<%= link_to 'Cancel Edit', admin_path, :class => 'btn btn-danger form-control' %>
			</div>
		</div>
</div>



<div class="big-margin"></div>

app/views/menus/index.html.erb
<h1>Menus#index</h1>
<p>Find me in app/views/menus/index.html.erb</p>

app/views/menus/new.html.erb
<div class="container">
		<div class="row">
			<div class="col-md-5 col-md-offset-3">


				<%= form_for Menu.create do |f| %>
				<h2>Create Menu Item</h2>

					<%= f.label :menu_item, value: 'Item Name' %>
					<%= f.text_field :menu_item, :class => 'form-control' %><br />

					<%= f.label :category, value: 'Category' %>
					<% categories = ["Breakfast", "Paninis", "Salads"] %>

					<%= f.select(:category, options_for_select(categories)) %><br />

					<%= f.label :description, value: 'Description (information about the menu item)' %>
					<%= f.text_field :description, :class => 'form-control' %><br />

					<%= f.label :price, value: 'Price (Decimal - 3 Digits)' %>
					<%= f.text_field :price, :class => 'form-control' %><br />


					<%= f.submit 'Create Item', :class => 'btn content-btn form-control' %>

				<% end %>
				<br />
					<a class="btn btn-danger form-control" href="/admin/<%= current_user.id.to_s %>">Cancel New Item</a>


			</div>
		</div>
</div>

<div class="big-margin"></div>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>The Cubby Hole NJ</title>
	</head>
	<body>
		<!-- begin header -->
		<div class="container-fluid main-header" id="home">
			<nav class="navbar navbar-fixed-top">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNav">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="/"><img src="assets/Cubbyhole2logo.png"></a>
					</div>
					<div class="collapse navbar-collapse" id="topNav">
						<ul class="nav navbar-nav navbar-right nav-btn">
							<li><a id="homeit"><i class="fa fa-home" style="font-size: 22px"></i> Home</a></li>
							<li><a id="aboutit" href="/menu"><i class="fa fa-newspaper-o" style="font-size: 22px"></i>  Menu </a></li>
						</li>
						<li><a id="contactit"><i class="fa fa-phone" style="font-size: 22px"></i>  Contact</a></li>
					</ul>
				</div>
			</div>
		</nav>
		
		<div class="margin">
			<div class="row main-nav">
				<div class="col-md-8 col-md-offset-2 text-center">
					<img src="assets/Cubbyhole2logo.png" class="img-responsive header-image">
					
				</div>
			</div>
		</div>
		<div class="margin-text">
		</div>
	</div>
</div>
<!-- begin first content -->
<div class="container-fluid first-content" id="about">
	<div class="container">
		<div class="margin-text"></div>
		<h2 class="first-content-title">About Us</h2>
		<div class="line-break"></div>
		<div class="row">
			<div class="margin-text"></div>
			<div class="col-md-12">
				<h4>The Cubby Hole</h4>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum, adipisci tempore obcaecati. Necessitatibus, consectetur commodi mollitia, qui hic in cum quasi suscipit atque laudantium facere veritatis! Doloribus aliquid recusandae, deserunt. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum ex eligendi modi totam deserunt quia consequuntur possimus omnis tempora facere tenetur, debitis excepturi. Error excepturi expedita consectetur sunt qui eius! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores velit, odit quam, quae expedita fugiat dicta eos, aspernatur quibusdam voluptatum consequuntur ut rem doloremque fuga corporis error sapiente aliquam possimus!. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit illo rerum nostrum sed praesentium numquam magni laboriosam. Quisquam ratione, assumenda delectus, facilis, minima vel provident porro officia obcaecati temporibus ducimus.</p>
			</div>
		</div>
	</div>
</div>
<div class="second-content-wrapper">
	<div class="second-content">
		<div class="row">
			<div class="col-md-4 col-md-offset-2">
				<img src="assets/cubby3-.jpg" style="width:80%">
				
			</div>
			<div class="col-md-3">
				<div class="margin-text"></div>
					<h3>Contact Us Now!</h3>
					<center><h4>55 E Main St #1<h4>
					<h4>Moorestown, New Jersey 08057</h4>
					<h4><i class="fa fa-mobile" style="font-size: 22px"></i> Phone: (856) 234-4372</h4></center>
				<div class="first-content-text">
				<h3>Our Menu</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla provident ut eveniet iste deleniti porro. Adipisci iste aut laudantium rem natus, tenetur, necessitatibus provident, nostrum expedita eaque ex consequatur ut! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores tempora, pariatur nam magnam atque fugit provident mollitia repudiandae, sapiente unde labore. Numquam alias nulla cumque quis veritatis veniam unde illo.</p>
				</div>
				<!-- <div class="margin-text"></div> -->
				<div class="btn-margin"></div>
				<center><button class="btn btn-lg content-btn"><a href='/menu'><i class="fa fa-arrow-circle-down" style="font-size: 22px"></i> Check out our Menu</a></button></center>
			</div>
		</div>
		
	</div>
	
</div>
<div class="third-content-wrapper" id="locate">
	<div class="third-content">
		<div class="container">
			<div class="row">
<!-- 				<div class="col-md-4">
					<div class="margin-text"></div>
					<h3>Our Menu</h3>
											

					<div class="margin-text"></div>
					<center><button class="btn btn-lg content-btn"><a href='/menu'>Check out our Menu</a></button></center>
				</div> -->
				<div class="col-md-6">
					<div class="margin-text"></div>
					<center><h3>Location</h3>
					</center>
											    <div id="map"></div>
						    <script>
						      function initMap() {
						        var uluru = {lat: 39.964, lng: -74.944};
						        var map = new google.maps.Map(document.getElementById('map'), {
						          zoom: 15,
						          center: uluru
						        });
						        var marker = new google.maps.Marker({
						          position: uluru,
						          map: map
						        });
						      }
						    </script>
						    <script async defer
						    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDQxxFBgvR3G8TaQ7Eg7xwD2pRxZsX1bNk&callback=initMap">
						    </script>
					<div class="margin-text"></div>
					<!-- image should go here -->
				</div>
				<div class="col-md-6">
					<div class="margin-text"></div>
					<h3>Hours</h3>
						<table class="table table-striped">
							<tbody>
								<tr>
									<td>Monday</td>
									<td class="hours">7:30AM - 3:00PM</td>
								</tr>

								<tr>
									<td>Tuesday</td>
									<td class="hours"> 7:30AM - 3:00PM</td>
								</tr>
								<tr>
									<td>Wednesday</td>
									<td class="hours">7:30AM - 3:00PM</td>
								</tr>

								<tr>
									<td>Thursday</td>
									<td class="hours">7:30AM - 3:00PM</td>
								</tr>

								<tr>
									<td>Friday</td>
									<td class="hours">7:30AM - 3:00PM</td>
								</tr>

								<tr>
									<td>Saturday</td>
									<td class="hours">7:30AM - 3:00PM</td>
								</tr>

								<tr>
									<td>Sunday</td>
									<td class="hours">7:30AM - 3:00PM</td>
								</tr>

							</tbody>

						</table>					
				</div>
			</div>
		</div>
	</div>
</div>
</div>
<div class="fourth-content-wrapper" id="contact">
<div class="fourth-content">
	<div class="container">
		<div class="col-md-12">
			<h3>Join Our Newsletter!</h3>
			<div class="margin-text"></div>
			<div class="row">
				<div class="col-md-6">
					<%= form_for Email.new do |f| %>
					<%= f.label :fname, 'First Name' %><br>
					<%= f.text_field :fname, :placeholder => "First Name", :class => 'form-control' %><br>
				</div>
				<div class="col-md-6">
					<%= f.label :lname, 'Last Name' %><br>
					<%= f.text_field :lname, :placeholder => "Last Name", :class => 'form-control' %><br>
				</div>
			</div>
			<%= f.label :email, 'Email' %><br>
			<%= f.text_field :email, :placeholder => "Email", :class => 'form-control' %><br>
			<%= f.submit 'Join Our Email List', :class => 'btn content-btn form-control' %>
			<% end %>
			
		</div>
	</div>
</div>
</div>
</div>
<!-- footer -->

</body>
</html>

app/views/static_pages/menu.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>The Cubby Hole NJ</title>
	</head>
	<body>
		<!-- begin header -->
		<div class="container-fluid menu-header" id="home">
			<nav class="navbar navbar-fixed-top">
				<div class="container-fluid">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNav">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="/"><img src="assets/Cubbyhole2logo.png"></a>
					</div>
					<div class="collapse navbar-collapse" id="topNav">
						<ul class="nav navbar-nav navbar-right nav-btn">
							<li><a href="/"><i class="fa fa-home" style="font-size: 22px"></i>Home</a></li>
						</ul>
					</div>
				</div>
			</nav>
			
			<div class="margin">
				<div class="row main-nav">
					<div class="col-md-8 col-md-offset-2 text-center">
						
						
					</div>
				</div>
			</div>
			<div class="margin-bot">
			</div>
		</div>
	</div>
	<!-- begin menu content -->
	<div class="container-fluid menu-content" id="about">
		<div class="container">
			<div class="margin"></div>
			<h2 class="first-content-title" style="text-align:left;">The Menu</h2>
			<div class="line-break"></div>
			<div class="row">
				<div class="margin-text"></div>
				<div class="col-md-12">
					<h4 style="text-align:left;">Breakfast</h4>
					<div class="line-break"></div>
					<% Menu.where(category: "Breakfast").each  do |breakfast | %>
					<div class="row">
						<div class="col-md-6">
							<h6><i class="fa fa-cutlery" aria-hidden="true"></i> <%= breakfast.menu_item %></h6><br>
							<p style="text-align: left;"><%= breakfast.description%></p>
						</div>
						
						<div class="col-md-1 col-md-offset-5">
							<h6><i class="fa fa-dollar" aria-hidden="true"></i> <%= breakfast.price %></h6><br>
						</div>
					</div>
					<% end %>
					<h4 style="text-align:left">Paninis</h4>
					<div class="line-break"></div>
					<% Menu.where(category: "Paninis").each  do |paninis| %>
					<div class="row">
						<div class="col-md-6">
							<h6><i class="fa fa-cutlery" aria-hidden="true"></i> <%= paninis.menu_item %></h6><br>
							<p style="text-align: left;"><%= paninis.description%></p>
						</div>
						<div class="col-md-1 col-md-offset-5">
							<h6><i class="fa fa-dollar" aria-hidden="true"></i> <%= paninis.price %></h6><br>
						</div>
					</div>
					<% end %>
					
					<h4 style="text-align:left">Salads</h4>
					<div class="line-break"></div>
					<% Menu.where(category: "Salads").each  do |salads| %>
					<div class="row">
						<div class="col-md-6">
							<h6><i class="fa fa-cutlery" aria-hidden="true"></i> <%= salads.menu_item %></h6><br>
							<p style="text-align: left;"><%= salads.description%></p>
						</div>
						<div class="col-md-1 col-md-offset-5">
							<h6><i class="fa fa-dollar" aria-hidden="true"></i> <%= salads.price %></h6><br>
						</div>
					</div>
					<% end %>
					
				</div>
				<div class="margin-bot"></div>
			</div>
		</div>
	</div>
	<!-- footer -->
	<footer>
		<div class="footer-wrap">
			
		</div>
	</footer>
	
</body>
</html>